-- Production target: ydiihvzcxaaoqhmgoqvu.supabase.co
-- PREPARED ONLY: requires explicit approval before production execution.
-- Adds 20 products for /guide/pokemon-vs-dragon-ball. Idempotent by slug.

BEGIN;

INSERT INTO public.products (
  slug, name, tagline, description, price_cents, currency, affiliate_url,
  image_url, image_urls, is_published, is_featured, shop_persona,
  shop_main_category, shop_sub_category, amazon_category, brand, shop_tags,
  editorial_note, key_fact, pros, cons
)
VALUES
('pokemon-pikachu-pluesch-30cm','Pokémon Pikachu Plüschfigur, 30 cm','Dreißig Zentimeter gute Laune mit roten Backen.','Offizielle Pikachu-Plüschfigur im handlichen Geschenkformat. Der Marketplace-Verkäufer und aktuelle Bestand sollten vor dem Kauf geprüft werden.',2318,'EUR','https://www.amazon.de/dp/B0BXSYGGZJ?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/613AzfqJGhL.jpg',ARRAY['https://m.media-amazon.com/images/I/613AzfqJGhL.jpg'],true,false,'miniboss','lifestyle','plueschfigur','Spielzeug','Pokémon',ARRAY['miniboss:lifestyle','pokemon','pikachu','plueschfigur'],'Das weichere Maskottchen im ersten Duell.','Pikachu-Plüschfigur mit etwa 30 cm Höhe.',ARRAY['bekanntes Motiv','gutes Geschenkformat'],ARRAY['Marketplace-Angebot']),
('dragon-ball-goku-pluesch-31cm','Play by Play Dragon Ball Goku Plüschtier, 31 cm','Kakarott, aber kuschelig.','Goku als 31 Zentimeter große Plüschfigur von Play by Play. Zum Recherchezeitpunkt war der Marketplace-Bestand knapp.',1399,'EUR','https://www.amazon.de/dp/B09HMXF2XH?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/6178xysk0GL.jpg',ARRAY['https://m.media-amazon.com/images/I/6178xysk0GL.jpg'],true,false,'miniboss','lifestyle','plueschfigur','Spielzeug','Play by Play',ARRAY['miniboss:lifestyle','dragon-ball','goku','plueschfigur'],'Günstiges Goku-Gegenstück zu Pikachu.','Goku-Plüschfigur mit etwa 31 cm Höhe.',ARRAY['günstiger Preis','klares Fanmotiv'],ARRAY['Marketplace','knapper Bestand möglich']),
('funko-pop-pikachu-games','Funko POP! Games Pokémon Pikachu','Pikachu mit großem Kopf. Also fast unverändert.','Pikachu als kompakte Funko-POP-Sammelfigur für Regal und Schreibtisch.',1361,'EUR','https://www.amazon.de/dp/B01MFX366P?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/71wx6IaqWuL.jpg',ARRAY['https://m.media-amazon.com/images/I/71wx6IaqWuL.jpg'],true,false,'babo','gaming','sammelfigur','Spielzeug','Funko',ARRAY['babo:gaming','pokemon','pikachu','funko'],'Direkt verfügbares kleines Sammlergeschenk.','Funko POP! Games Figur von Pikachu.',ARRAY['Amazon-Angebot','günstiger Einstieg'],ARRAY['reine Deko']),
('funko-pop-super-saiyan-goku-first-appearance','Funko POP! Dragon Ball Z Super-Saiyajin-Goku','Die Frisur gewinnt bereits vor Kampfbeginn.','Super-Saiyajin-Goku aus der First-Appearance-Welle als Funko-Sammelfigur.',1549,'EUR','https://www.amazon.de/dp/B085PHL1M2?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/714PODhHChL.jpg',ARRAY['https://m.media-amazon.com/images/I/714PODhHChL.jpg'],true,false,'babo','gaming','sammelfigur','Spielzeug','Funko',ARRAY['babo:gaming','dragon-ball','goku','funko'],'Das direkte Funko-Gegenstück zu Pikachu.','Funko POP! von Super-Saiyajin-Goku.',ARRAY['Amazon-Angebot','ikonische Form'],ARRAY['ältere Produktwelle']),
('pokemon-dunkelnacht-booster-display-36','Pokémon Dunkelnacht Booster-Display mit 36 Boostern','Sechsunddreißigmal Folie öffnen und Hoffnung verwalten.','Versiegeltes deutsches Pokémon-TCG-Display mit 36 Boostern. Marketplace-Preis und Bestand vor dem Kauf vergleichen.',24298,'EUR','https://www.amazon.de/dp/B0HCJQL1K8?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/81HVt68-Z5L.jpg',ARRAY['https://m.media-amazon.com/images/I/81HVt68-Z5L.jpg'],true,false,'babo','gaming','sammelkarten','Spielzeug','Pokémon',ARRAY['babo:gaming','pokemon','tcg','booster-display'],'Das größere der beiden TCG-Displays.','Deutsches Display mit 36 Boostern.',ARRAY['36 Booster','deutsche Ausgabe'],ARRAY['hoher Marketplace-Preis','knapper Bestand']),
('dragon-ball-fusion-world-new-adventure-fb05-booster-box','Dragon Ball Super Fusion World New Adventure FB05 Booster Box','Vierundzwanzig Booster und kein Dragon Radar nötig.','Versiegelte Dragon-Ball-Super-Fusion-World-Boosterbox New Adventure FB05 mit 24 Packs.',22999,'EUR','https://www.amazon.de/dp/B0DWVCVZ89?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/71Y7jS1+OGL.jpg',ARRAY['https://m.media-amazon.com/images/I/71Y7jS1+OGL.jpg'],true,false,'babo','gaming','sammelkarten','Spielzeug','Bandai',ARRAY['babo:gaming','dragon-ball','fusion-world','booster-box'],'Das Dragon-Ball-Gegenstück im Karten-Duell.','FB05-Boosterbox mit 24 Packs.',ARRAY['versiegeltes Display','Bandai TCG'],ARRAY['Marketplace','teuer pro Booster']),
('pokemon-die-ersten-abenteuer-band-1','Pokémon: Die ersten Abenteuer 01 – Rot, Grün und Blau','Der Anfang, bevor der Pokédex zur Lebensaufgabe wurde.','Deutscher erster Band der Pokémon-Manga-Reihe von Hidenori Kusaka und Mato.',699,'EUR','https://www.amazon.de/dp/3957986362?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/81apKGX62FL.jpg',ARRAY['https://m.media-amazon.com/images/I/81apKGX62FL.jpg'],true,false,'miniboss','gaming','manga','Bücher','Panini Manga',ARRAY['miniboss:gaming','pokemon','manga','band-1'],'Der günstige Einstieg in die Pokémon-Manga-Reihe.','Deutsche Ausgabe, Band 1.',ARRAY['Amazon-Angebot','günstiger Einstieg'],ARRAY['Serienstart kann Folgekauf auslösen']),
('dragon-ball-wie-alles-begann-band-1','Dragon Ball 1: Wie alles begann','Der Anfang, als ein Drache noch das große Problem war.','Deutscher erster Band von Akira Toriyamas Dragon-Ball-Manga.',700,'EUR','https://www.amazon.de/dp/3551732930?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/51GswM36eIL.jpg',ARRAY['https://m.media-amazon.com/images/I/51GswM36eIL.jpg'],true,false,'babo','gaming','manga','Bücher','Carlsen Manga',ARRAY['babo:gaming','dragon-ball','manga','band-1'],'Preislich fast identisches Gegenstück zum Pokémon-Manga.','Deutsche Ausgabe des ersten Dragon-Ball-Bandes.',ARRAY['Amazon-Angebot','Klassiker'],ARRAY['Serienstart kann Folgekauf auslösen']),
('pokemon-glurak-select-actionfigur-15cm','Pokémon Select Glurak Actionfigur, 15 cm','Glurak steht. Hoffentlich hält der Standfuß.','Bewegliche Glurak-Sammelfigur von Jazwares mit mehr als 15 Gelenkpunkten und Standfuß.',2362,'EUR','https://www.amazon.de/dp/B08T6BDDZQ?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/61Ljg1r5hyL._AC_SX679_.jpg',ARRAY['https://m.media-amazon.com/images/I/61Ljg1r5hyL._AC_SX679_.jpg'],true,false,'babo','gaming','actionfigur','Spielzeug','Jazwares',ARRAY['babo:gaming','pokemon','glurak','actionfigur'],'Fairer Größen- und Preisvergleich mit Goku.','Etwa 15 cm große bewegliche Glurak-Figur.',ARRAY['viele Gelenkpunkte','starke Bewertungen'],ARRAY['Standfuß laut Einzelrezension empfindlich']),
('dragon-ball-dragon-stars-goku-actionfigur-17cm','Bandai Dragon Stars Goku Actionfigur, 17 cm','Sechzehn Gelenke, null Geduld.','Offiziell bezeichnete Dragon-Stars-Goku-Actionfigur von Bandai mit 16 Gelenkpunkten.',2531,'EUR','https://www.amazon.de/dp/B08C88HDK6?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/71TvMPRPGnL._AC_SX679_.jpg',ARRAY['https://m.media-amazon.com/images/I/71TvMPRPGnL._AC_SX679_.jpg'],true,false,'babo','gaming','actionfigur','Spielzeug','Bandai',ARRAY['babo:gaming','dragon-ball','goku','actionfigur'],'Nahezu gleich großes Gegenstück zur Glurak-Figur.','17 cm große Goku-Figur mit 16 Gelenkpunkten.',ARRAY['Amazon-Angebot','viele Bewertungen'],ARRAY['für die Größe nicht günstig']),
('cypbrands-pokemon-geo-kinderrucksack-30cm','CYPBRANDS Pokémon Geo Kinderrucksack, 30 cm','Pikachu trägt heute die Brotdose.','Schwarzer lizenzierter Pokémon-Kinderrucksack von CYPBRANDS im 30-Zentimeter-Format.',2495,'EUR','https://www.amazon.de/dp/B0DL6FTBNH?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/71cqjXQssJL._AC_SX300_SY300_QL70_ML2_.jpg',ARRAY['https://m.media-amazon.com/images/I/71cqjXQssJL._AC_SX300_SY300_QL70_ML2_.jpg'],true,false,'miniboss','lifestyle','rucksack','Bekleidung','CYPBRANDS',ARRAY['miniboss:lifestyle','pokemon','rucksack','kinder'],'Gleicher Hersteller und gleiche Größe wie das Gegenstück.','30 cm großer Pokémon-Kinderrucksack.',ARRAY['offiziell bezeichnet','kompaktes Kinderformat'],ARRAY['wenige Bewertungen','Maße prüfen']),
('cypbrands-dragon-ball-goku-kinderrucksack-30cm','CYPBRANDS Dragon Ball Goku Kinderrucksack, 30 cm','Training beginnt mit der eigenen Brotdose.','Schwarzer offiziell bezeichneter Dragon-Ball-Kinderrucksack von CYPBRANDS im 30-Zentimeter-Format.',1399,'EUR','https://www.amazon.de/dp/B0F9LGQ64Y?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/71dOlOUVrAL._AC_SX679_.jpg',ARRAY['https://m.media-amazon.com/images/I/71dOlOUVrAL._AC_SX679_.jpg'],true,false,'miniboss','lifestyle','rucksack','Bekleidung','CYPBRANDS',ARRAY['miniboss:lifestyle','dragon-ball','goku','rucksack'],'Preislich stärkeres Gegenstück vom selben Hersteller.','30 cm großer Dragon-Ball-Kinderrucksack.',ARRAY['Amazon-Angebot','günstiger Preis'],ARRAY['wenige Bewertungen']),
('pokemon-pikachu-kinder-bademantel','Pokémon Pikachu Kinder-Bademantel mit 3D-Ohren','Pikachu vor der Schule, nur trockener.','Fleece-Bademantel für Kinder in den Größen 116 bis 158 mit Pikachu-Motiv und 3D-Ohren.',3799,'EUR','https://www.amazon.de/dp/B0FY6P63LL?tag=geeklist-21&linkCode=ogi&th=1&psc=1','https://m.media-amazon.com/images/I/717q6vPcimL._AC_SY879_.jpg',ARRAY['https://m.media-amazon.com/images/I/717q6vPcimL._AC_SY879_.jpg'],true,false,'miniboss','lifestyle','bademantel','Bekleidung','Pokémon',ARRAY['miniboss:lifestyle','pokemon','pikachu','bademantel'],'Benutzerwahl; starkes Markensignal und direkte Lieferbarkeit.','Kindergrößen 116 bis 158; 3D-Ohren.',ARRAY['Amazon-Versand','starkes Markensignal'],ARRAY['nur Kindergrößen','kleine Bewertungsbasis']),
('dragon-ball-z-herren-bademantel-schwarz','Dragon Ball Z Herren-Bademantel mit Taschen und Gürtel','Goku für den Sonntag ohne Trainingsplan.','Schwarzer Herren-Bademantel in den Größen S bis 3XL. Das Angebot kommt aus den USA und besitzt aktuell keine hervorgehobene Buy Box.',4351,'EUR','https://www.amazon.de/dp/B0CZRZ3ZKY?tag=geeklist-21&linkCode=ogi&th=1&psc=1','https://m.media-amazon.com/images/I/81PnBXlnHEL._AC_SX679_.jpg',ARRAY['https://m.media-amazon.com/images/I/81PnBXlnHEL._AC_SX679_.jpg'],true,false,'babo','lifestyle','bademantel','Bekleidung','Dragon Ball Z',ARRAY['babo:lifestyle','dragon-ball','goku','bademantel','import'],'Benutzerwahl; Import und Lizenzunsicherheit werden ausdrücklich genannt.','Herren-Bademantel, Größen S bis 3XL.',ARRAY['breite Größenauswahl','viele Bewertungen'],ARRAY['keine Buy Box','USA-Import','Lizenzsignal nicht unabhängig bestätigt']),
('ravensburger-pokemon-challenge-puzzle-1000','Ravensburger Challenge Pokémon Puzzle, 1000 Teile','Tausend Teile und Pikachu hilft nicht.','Pokémon-Challenge-Puzzle von Ravensburger mit 1000 Teilen.',899,'EUR','https://www.amazon.de/dp/B0CQ8CR1PX?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/91IdueZOeAL.jpg',ARRAY['https://m.media-amazon.com/images/I/91IdueZOeAL.jpg'],true,false,'babo','gaming','puzzle','Spielzeug','Ravensburger',ARRAY['babo:gaming','pokemon','puzzle','1000-teile'],'Günstiges Markenpuzzle mit direktem Amazon-Angebot.','Pokémon-Puzzle mit 1000 Teilen.',ARRAY['Amazon-Angebot','bekannter Hersteller'],ARRAY['Challenge-Motiv bewusst schwierig']),
('clementoni-dragon-ball-puzzle-1000','Clementoni Dragon Ball Puzzle, 1000 Teile','Tausend Teile, diesmal mit mehr Geschrei.','Dragon-Ball-Puzzle von Clementoni mit 1000 Teilen und einem Format von etwa 70 mal 50 Zentimetern.',1099,'EUR','https://www.amazon.de/dp/B0CYTTT2FM?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/81qESNnf2EL.jpg',ARRAY['https://m.media-amazon.com/images/I/81qESNnf2EL.jpg'],true,false,'babo','gaming','puzzle','Spielzeug','Clementoni',ARRAY['babo:gaming','dragon-ball','puzzle','1000-teile'],'Direktes Gegenstück in derselben Teileklasse.','Dragon-Ball-Puzzle mit 1000 Teilen.',ARRAY['bekannter Hersteller','gleiches Format'],ARRAY['Marketplace','knapper Bestand']),
('pokemon-legenden-za-switch-2','Pokémon-Legenden: Z-A – Nintendo Switch 2 Edition','Monster sammeln, Stadt erkunden, Termine absagen.','Pokémon-Legenden Z-A in der Nintendo-Switch-2-Edition als aktuelles Sammel- und Rollenspiel.',3999,'EUR','https://www.amazon.de/dp/B0FBMHQ8LS?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/51z615Y6NGL.jpg',ARRAY['https://m.media-amazon.com/images/I/51z615Y6NGL.jpg'],true,false,'babo','gaming','videospiel','Games','Nintendo',ARRAY['babo:gaming','pokemon','switch-2','videospiel'],'Aktuelles Nintendo-Spiel im direkten Plattformvergleich.','Nintendo-Switch-2-Edition von Pokémon-Legenden Z-A.',ARRAY['Amazon-Angebot','aktueller Titel'],ARRAY['Switch-2-Version vor Kauf prüfen']),
('dragon-ball-sparking-zero-switch','Dragon Ball: Sparking! Zero für Nintendo Switch','Der Bildschirm bekommt heute Überstunden.','Dragon Ball Sparking Zero für Nintendo Switch mit Fokus auf große Arenakämpfe und bekannte Figuren.',4399,'EUR','https://www.amazon.de/dp/B0FKT4W5NX?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/51aCoPGuWcL.jpg',ARRAY['https://m.media-amazon.com/images/I/51aCoPGuWcL.jpg'],true,false,'babo','gaming','videospiel','Games','Bandai Namco',ARRAY['babo:gaming','dragon-ball','switch','videospiel'],'Aktueller Dragon-Ball-Titel im Switch-Duell.','Nintendo-Switch-Ausgabe von Dragon Ball Sparking Zero.',ARRAY['Amazon-Angebot','aktueller Titel'],ARRAY['Plattformversion vor Kauf prüfen']),
('teknofun-pokemon-glurak-sunset-leuchte','TEKNOFUN Pokémon Glurak Sunset Leuchtdekoration, 20 cm','Glurak macht Licht, ohne die Wohnung anzuzünden.','20 Zentimeter große Pokémon-Leuchtdekoration im Glurak-Sunset-Design mit USB-C-Anschluss.',2999,'EUR','https://www.amazon.de/dp/B0FZK47ZGV?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/71QdPqpOiJL._AC_SY300_SX300_QL70_ML2_.jpg',ARRAY['https://m.media-amazon.com/images/I/71QdPqpOiJL._AC_SY300_SX300_QL70_ML2_.jpg'],true,false,'babo','gaming','beleuchtung','Beleuchtung','TEKNOFUN',ARRAY['babo:gaming','pokemon','glurak','lampe','usb-c'],'Nahezu identisches Gegenstück zur Goku-Leuchte.','20 cm, USB-C, offizielles Produkt laut Listing.',ARRAY['Amazon-Angebot','starkes Motiv'],ARRAY['sehr wenige Bewertungen']),
('teknofun-dragon-ball-goku-ultra-instinct-leuchte','TEKNOFUN Dragon Ball Goku Ultra Instinct Leuchtdekoration, 20 cm','Ultra Instinct für den Schreibtisch.','20 Zentimeter große Dragon-Ball-Super-Leuchtdekoration mit Goku im Ultra-Instinct-Design und USB-C-Anschluss.',2999,'EUR','https://www.amazon.de/dp/B0FTFQBNQM?tag=geeklist-21&linkCode=ogi&th=1','https://m.media-amazon.com/images/I/71j-1OeVxsL._AC_SX679_.jpg',ARRAY['https://m.media-amazon.com/images/I/71j-1OeVxsL._AC_SX679_.jpg'],true,false,'babo','gaming','beleuchtung','Beleuchtung','TEKNOFUN',ARRAY['babo:gaming','dragon-ball','goku','lampe','usb-c'],'Gleicher Hersteller, Preis und Format wie Glurak.','20 cm, USB-C, offizielles Toei-Produkt laut Listing.',ARRAY['Amazon-Angebot','starkes Motiv'],ARRAY['noch keine Rezensionen','knapper Bestand möglich'])
ON CONFLICT (slug) DO UPDATE SET
  name=EXCLUDED.name, tagline=EXCLUDED.tagline, description=EXCLUDED.description,
  price_cents=EXCLUDED.price_cents, currency=EXCLUDED.currency,
  affiliate_url=EXCLUDED.affiliate_url, image_url=EXCLUDED.image_url,
  image_urls=EXCLUDED.image_urls, is_published=EXCLUDED.is_published,
  shop_persona=EXCLUDED.shop_persona, shop_main_category=EXCLUDED.shop_main_category,
  shop_sub_category=EXCLUDED.shop_sub_category, amazon_category=EXCLUDED.amazon_category,
  brand=EXCLUDED.brand, shop_tags=EXCLUDED.shop_tags,
  editorial_note=EXCLUDED.editorial_note, key_fact=EXCLUDED.key_fact,
  pros=EXCLUDED.pros, cons=EXCLUDED.cons;

DO $$
DECLARE n integer;
BEGIN
  SELECT count(*) INTO n FROM public.products
  WHERE affiliate_url ~ '/(B0BXSYGGZJ|B09HMXF2XH|B01MFX366P|B085PHL1M2|B0HCJQL1K8|B0DWVCVZ89|3957986362|3551732930|B08T6BDDZQ|B08C88HDK6|B0DL6FTBNH|B0F9LGQ64Y|B0FY6P63LL|B0CZRZ3ZKY|B0CQ8CR1PX|B0CYTTT2FM|B0FBMHQ8LS|B0FKT4W5NX|B0FZK47ZGV|B0FTFQBNQM)([/?]|$)'
    AND is_published=true;
  IF n <> 20 THEN RAISE EXCEPTION 'Postflight failed: expected 20 published ASINs/ISBNs, found %', n; END IF;
END $$;

COMMIT;

SELECT slug,name,price_cents,affiliate_url,is_published
FROM public.products
WHERE affiliate_url ~ '/(B0BXSYGGZJ|B09HMXF2XH|B01MFX366P|B085PHL1M2|B0HCJQL1K8|B0DWVCVZ89|3957986362|3551732930|B08T6BDDZQ|B08C88HDK6|B0DL6FTBNH|B0F9LGQ64Y|B0FY6P63LL|B0CZRZ3ZKY|B0CQ8CR1PX|B0CYTTT2FM|B0FBMHQ8LS|B0FKT4W5NX|B0FZK47ZGV|B0FTFQBNQM)([/?]|$)'
ORDER BY slug;
