#!/usr/bin/env python3
import requests
import time

SUPABASE_URL = "https://ydiihvzcxaaoqhmgoqvu.supabase.co"
SERVICE_KEY = "***REDACTED***"

HEADERS = {
    "apikey": SERVICE_KEY,
    "Authorization": f"Bearer {SERVICE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal"
}

notes = {
    "superone-zigarettenanzuender-schnellladegeraet": "Haben wir erst belächelt, dann täglich benutzt. Wer oft im Auto lädt und mehrere Geräte gleichzeitig anschließen will, dem fehlt so ein Ding danach irgendwie.",
    "lichtschwert-metallgriff-erwachsene": "Klar ist das ein Spielzeug für Erwachsene — aber der Metallgriff macht den Unterschied. Kein Plastikschrott aus dem Supermarkt, das Ding sieht tatsächlich aus wie aus dem Film.",
    "dicmky-hoehenverstellbarer-schreibtisch-aufsatz": "Die ersten zwei Wochen fühlt sich Stehen am Schreibtisch seltsam an. Danach willst du nicht zurück. Wer Home Office macht und Rückenprobleme kennt — das hier ist der erste sinnvolle Schritt.",
    "lifepro-infrarot-saunadecke": "Nicht für jeden — wer Hitze nicht mag, wird das hier schnell wieder verkaufen. Wer aber nach Sport oder einem langen Tag in Wärme versinken will, ohne irgendwo hinfahren zu müssen: funktioniert.",
    "joto-wasserdichte-handyhuelle-unterwasser": "Günstig, zuverlässig, und man braucht es genau dann wenn man es nicht dabei hat. Am Strand, am Pool, beim Rafting — ein No-Brainer für unter 15 Euro.",
    "newl-reflektierende-holographic-windbreaker": "Polarisiert. Die einen finden es zu viel, die anderen zu wenig. Wir finden: genau richtig für alle die nachts sicher sein wollen ohne wie eine Warnweste auszusehen.",
    "tosy-flying-disc-wiederaufladbar": "Das klassische Frisbee aber mit LEDs — klingt nach Gimmick, macht abends draußen aber wirklich mehr Spaß als das Original. Aufladbar bedeutet auch: kein Batteriewechsel-Stress.",
    "jdvootd-programmierbare-led-laufschrift-tafel": "Für die Wohnung vielleicht zu viel, als Gag-Geschenk oder fürs Büro-Fenster aber ein absoluter Hingucker. Wer seinen Mitbewohnern Nachrichten hinterlassen will — das hier ist die Eskalationsstufe.",
    "personalisiertes-led-nachtlicht-jugendzimmer": "Kinder lieben personalisierten Kram — das ist kein Geheimnis. Nachtlicht mit eigenem Namen schlägt aber jedes generische Geschenk. Für Geburtstage die man nicht vergessen soll.",
    "eisroller-gesicht-augen-hautpflege": "Morgendlich geschwollene Augen — das Eisroller-Ritual ist simpel und es funktioniert. Nicht wegen Magie, sondern weil Kälte abschwillt. Im Kühlschrank lagern, morgens drüber rollen, fertig.",
    "fentec-schwebendes-buecherregal": "Sieht auf Fotos besser aus als in Wirklichkeit — wenn man aber die richtige Wand hat und nicht zu viele schwere Bücher nimmt, ist der Effekt wirklich beeindruckend. Nichts für 200 Seiten Wälzer.",
    "brubaker-weinflaschenhalter-totenkopf": "Ein Weinhalter der aussieht als käme er aus einem Piratenfilm. Wer seinen Keller etwas düsterer gestalten will oder einen Gesprächsstarter auf dem Tisch braucht — hier ist er.",
    "mayflash-f300-arcade-joystick": "Für Fighting Games am PC oder auf der Konsole ist ein Arcade-Stick einfach das richtige Werkzeug. Dieser hier ist solide ohne den Preisbereich zu sprengen — gut für den Einstieg.",
    "eiswuerfelform-lebensmittelechte": "Eiswürfel aus dem Standardtray sind schön und gut. Diese hier machen aber größere Würfel die langsamer schmelzen und das Getränk nicht verwässern. Wer Whisky oder Cocktails trinkt — lohnt sich.",
    "tre-feuerstahl-xxl": "XXL bedeutet hier wirklich XXL — der Griff liegt gut in der Hand und der Stab ist groß genug dass man nicht nervös wird beim Schlagen. Für Camping oder als Notfall-Backup im Rucksack sinnvoll.",
    "magnetisches-whiteboard-kontaktpapier-selbstklebend": "Bohren ist nervig. Dieses Kontaktpapier klebt, funktioniert als Whiteboard und lässt sich rückstandslos abziehen. Für Mieter oder alle die ihren Vermieter nicht ärgern wollen: sehr praktisch.",
    "fenree-business-rucksack-wasserdicht-usb": "Viele Rucksäcke nennen sich wasserdicht und meinen damit \"kurzer Nieselregen\". Dieser hält tatsächlich was er verspricht — und der USB-Port ist für Pendelfahrten ein echter Komfort.",
    "nelux-3er-pack-planet-wolke-nachtlicht": "Drei Nachtlichter, drei Planeten-Designs, ein Preis — macht das Kinderzimmer zu einem kleinen Planetarium. Einfach in die Steckdose, keine Installation, sieht trotzdem gut aus.",
    "ckb-retro-kaugummi-maschine-suessigkeitenspender": "Nostalgie-Faktor hoch, Nutzwert überraschend real. Wer kleine Geschwister oder Neffen/Nichten beschenken will — die Reaktion ist garantiert.",
    "protoarc-xk01-bluetooth-klappbare-tastatur": "Für unterwegs mit iPad oder Handy ist eine Klapptastatur ein Game-Changer. Diese hier ist nicht die dünnste, aber die Tasten haben einen guten Hub — man tippt nicht ins Leere.",
    "porseme-ultraschall-luftbefeuchter-farbwechsel": "Luftbefeuchter sind im Winter für trockene Heizungsluft sinnvoll, das weiß jeder. Dieser hat dabei noch ein angenehmes Licht-Moodfeature — kein Highlight, aber eine nette Zugabe.",
    "kaffeewaermer-tassenwaermer-elektrisch": "Der Moment wenn man seinen Kaffee vergisst und zum dritten Mal aufwärmt — kennt jeder. Ein Tassenwärmer löst das Problem still und ohne Aufwand. Kleines Gadget, echter Nutzen.",
    "wiederaufladbares-angelzubehoer-set": "Leuchtendes Angelzubehör klingt nach Marketing — ist es aber nicht. Nachts oder in trübem Wasser macht der Sichtunterschied einen echten Unterschied. Für Angler, die es ernst nehmen.",
    "rgb-gaming-mauspad-led-schreibtischpad": "Das Schreibtischpad schützt die Oberfläche und die LEDs sehen gut aus — keine Raketenwissenschaft. Wer seinen Setup aufwerten will ohne viel auszugeben: hier ist der einfachste Einstieg.",
    "personalisiertes-leuchtschild-wanddekoration": "Leuchtschilder mit eigenem Namen sind mittlerweile ein Klassiker — aber dieser Klassiker funktioniert noch immer. Für Kinderzimmer, Büros oder als Geschenk das persönlich wirkt.",
    "sternenhimmel-nachtlicht-sternenprojektor": "Den Projektor an die Decke halten, Schalter umlegen, Sternenhimmel. Kein aufwändiger Aufbau, keine Installation. Für Kinder zum Einschlafen oder Erwachsene die sich das gönnen wollen.",
    "yuandian-dodo-duck-led-nachtlicht": "Eine beleuchtete Ente auf dem Nachttisch ist eigentlich Unsinn. Und trotzdem kauft man das und findet es charmant. Manchmal reicht das.",
    "findchic-edelstahl-drehring": "Drehend, beruhigend, unauffällig — ein Fidget-Ring für alle die etwas in den Händen haben müssen ohne dass es auffällt. Besser als auf dem Tisch zu trommeln.",
    "mangoschneider-fruchthalter": "Mango schneiden ohne so ein Gerät ist eine klebrige Angelegenheit. Mit dem Schneider geht es in Sekunden und die Stücke sehen ordentlich aus. Für Mangofans kein Luxus sondern Pflicht.",
    "yusing-gaming-haengevitrine-regal": "Wer Figuren oder Controller-Sammlung hat und sie nicht in einer Kiste vergraben will: dieses Regal ist eine günstige Lösung die tatsächlich gut aussieht. Montage ist nicht komplex.",
    "joyroom-kabelmanagement-schreibtisch-selbstklebend": "Kabelchaos unter dem Schreibtisch ist das unglamouröse Problem das jeder hat und keiner löst. Dieses System ist nicht perfekt aber eine deutliche Verbesserung gegenüber dem Status quo.",
    "reise-haengematte-nylon-schnelltrocknend": "Ultraleichte Nylonhängematte passt in eine Faust, wiegt fast nichts, und kann zwischen zwei Bäumen hängen bevor der andere sein Zelt aufgebaut hat. Für Rucksackreisende ein Muss.",
    "derayee-schaumstoff-wasserpistole": "Schaumstoff-Wasserpistolen sind für Kinder gedacht — werden aber erfahrungsgemäß von Erwachsenen bei Grillabenden übernommen. Kein Kommentar.",
    "ticktime-tk3-wuerfel-timer-countdown": "Umdrehen statt drücken — das ist das ganze Konzept. Und es funktioniert weil es keine Nachdenken erfordert. Gut für Pomodoro, Brettspiele oder alle die Zeit nicht im Blick behalten können.",
    "anker-usb-c-adapter-upgraded": "Anker macht solide Adapter und dieser ist keine Ausnahme. USB-C-Chaos endet irgendwann wenn man die richtigen Adapter hat — dieser gehört dazu.",
    "inner-peace-meditationskissen-yogakissen": "Wer auf dem Boden meditiert und danach Knieschmerzen hat — das Kissen ist die Lösung. Klingt banal, macht aber einen echten Unterschied wenn man regelmäßig sitzt.",
    "mfi-zertifiziert-magsafe-wireless-ladestation-15w": "MagSafe funktioniert, und 15W sind die maximale Ladeleistung für iPhones. Wer Kabel leid ist und ein MagSafe-kompatibles iPhone hat: einfach drauflegen, fertig.",
    "fussmassage-igelball-faszienrolle": "Den Igelball unter den Fuß, rollen, winken. Nach langen Tagen im Stehen oder nach Sport ist das eine der einfachsten Möglichkeiten die Füße zu entspannen — kein Termin nötig.",
    "6-teiliges-schubladen-ordnungssystem": "Jede Schublade hat ein Chaos-Problem. Dieses System löst es in zehn Minuten. Keine Schrauben, kein Aufbau — einfach reinlegen und fertig. Der Unterschied ist sofort.",
    "diycut-taco-staender": "Jeder Taco-Abend kennt das Problem: die Schale kippt beim Befüllen um. Dieses Ding hält sie aufrecht und kostet praktisch nichts. Kleine Lösung, echter Unterschied.",
    "peleg-design-pastail-walfoermiges-nudelsieb": "Ein Nudelsieb in Walform — unnötig und trotzdem kauft man es. Weil es beim Kochen Gesprächsstoff bietet und weil Pasta abgießen mit einem Wal einfach besser ist.",
    "ubergames-riesenwackelturm-jumbo-jenga": "Normales Jenga kennt jeder. Wenn die Steine so groß sind dass man mit beiden Händen zieht — dann wird es ernst. Für Grillabende und Partys ein garantierter Mitspieler.",
    "kiayoo-wackelfigur-armaturenbrett-auto": "Wackelfiguren sind das vielleicht ehrlichste Gadget der Welt: kein Anspruch, nur Freude. Im Auto auf dem Armaturenbrett klebt so eine Figur und wackelt bei jedem Schlagloch. Reicht.",
    "vivo-hoehenverstellbares-stehpult": "Ein dediziertes Stehpult ist stabiler und ergonomischer als ein Aufsatz — für alle die täglich mehrere Stunden am Schreibtisch verbringen ist das hier die durchdachtere Lösung.",
    "asdirne-pizzaschneider-edelstahl": "Edelstahl, gut in der Hand, schneidet durch Pizza ohne zu haken — was man von einem Pizzaschneider erwartet. Wer noch einen aus Plastik benutzt wird nicht zurückwollen.",
    "trekline-multifunktionsmesser-rostfrei": "Kein Schweizer Taschenmesser aber ein solides Alltagsmultitool das man tatsächlich benutzt statt irgendwo im Schrank zu lagern. Für den Rucksack oder die Schreibtischschublade.",
    "einhorn-jahresvorrat-kondome": "52 Kondome in bunten Verpackungen — als Geschenk lustig, als Jahresvorrat praktisch, als Statement unübertroffen. Das ist Einhorn.",
    "mad-monkey-retro-spielekonsole": "400 Spiele, Hosentaschenformat, direkt per HDMI an den Fernseher. Für Retro-Nostalgiker ein Spaßobjekt — niemand erwartet hier Heimkonsolen-Qualität, aber das ist auch nicht der Punkt.",
    "kytok-controller-staender-4-etagen": "Vier Controller, vier Ebenen, ein Ständer — klar und simpel. Wer mehrere Controller herumliegen hat und endlich Ordnung will: hier.",
    "joyroom-brillenhalter-auto-sonnenblende": "Klingt nach einem dieser unnötigen Auto-Gadgets. Ist aber tatsächlich praktisch wenn man zwischen Sonnenbrille drinnen und draußen wechselt und sie nie griffbereit hat.",
    "elektrisches-nackenmassagegeraet-schultermassage": "Elektrische Massagegeräte variieren stark in der Qualität — dieses hier macht es richtig. Für Nacken und Schulter nach langen Schreibtischtagen eine echte Erleichterung ohne Termin.",
    "schildkroete-solarlaternen-metall-haengedeko": "Solar, kein Kabel, Schildkrötenform — im Garten oder auf dem Balkon hängt das und leuchtet einfach. Kein Aufwand, sieht gut aus, macht jeden Abend draußen gemütlicher.",
    "livondo-terracotta-pflanzenbewaesserung": "Die Terracotta-Spikes geben Wasser langsam ab — funktioniert besonders gut für alle die auf Reisen gehen oder einfach vergesslich sind. Kein Strom, kein Timer, nur Physik.",
    "fingerabdruck-vorhaengeschloss-eseesmart": "Schloss aufmachen ohne Schlüssel klingt nach Sci-Fi, ist aber längst Alltag. Für Spinde, Koffer oder den Gartenschuppen — wenn man den Schlüssel immer verliert ist das hier eine ernsthafte Option.",
    "shuffleboard-tischset-curling-familienspiel": "Curling ohne Eis und ohne Aufwand — dieses Tischset macht das Spielprinzip für Zuhause zugänglich. Für Familien die ein neues Spiel suchen das auch Erwachsene ernst nehmen.",
    "mond-deckenlampe-mit-fernbedienung": "Eine Deckenlampe die wie der Mond aussieht ist definitiv ein Statement. Für Kinderzimmer fast zu gut — für Schlafzimmer genau richtig wenn man Stimmungslicht mag.",
    "starthilfe-powerbank-7000a-booster": "Eine Starthilfe die in die Handtasche passt und trotzdem 7000A liefert klingt unrealistisch — ist es aber nicht. Einmal im Handschuhfach haben und nie wieder auf den ADAC warten.",
    "pizza-socks-box-pepperoni": "Socken die wie Pizzastücke aussehen und in einer Pizzaschachtel kommen. Als Weihnachtsgeschenk oder Geburtstagsmitbringsel wenn man keine Idee hat aber trotzdem Eindruck machen will.",
    "edelstahl-spaghettimass-portionierer": "Jeder kocht zu viel Pasta. Das ist eine Tatsache. Dieses kleine Ding löst genau das — einfach die Spaghetti durchstecken und man weiß wie viel man nimmt. Jahrelanger Begleiter.",
    "eiswuerfelform-todesstern-star-wars": "Eiswürfel in Todesstern-Form machen keinen besseren Drink — aber sie machen jeden Drink besser. Für Star Wars Fans kein Wahlrecht, für alle anderen ein guter Gesprächsstarter.",
    "empation-cocktailshaker-set": "Ein ordentliches Shaker-Set ist der erste Schritt zur Heimbar die man tatsächlich benutzt. Wer öfter Gäste hat oder einfach seinen Gin Tonic selbst mixen will — das hier ist der Einstieg.",
    "one-piece-ramen-schuessel-mit-staebchen": "Anime-Aesthetics in der Küche — entweder man liebt es oder man versteht es nicht. Für One Piece Fans ist das keine Frage. Für alle anderen: es ist tatsächlich eine funktionale Schüssel.",
    "azengear-paracord-survival-armband-set": "Paracord-Armbänder sehen gut aus und haben im Notfall echten Nutzen — das ist die seltene Kombination. Als Set ideal für Camping-Ausflüge zu zweit oder als Geschenk.",
    "rfid-blocker-karte-neueste-technologie": "Ob RFID-Klau wirklich ein Massenphänomen ist — diskutabel. Eine dünne Karte im Geldbeutel die das verhindert kostet aber kaum etwas und gibt Sicherheit. Kein schlechtes Verhältnis.",
    "wasserfilter-trinkflasche-edelstahl": "Unterwegs immer sauberes Wasser haben ohne Plastikflaschen kaufen zu müssen — das ist der Deal. Für Reisen in Länder mit schlechtem Leitungswasser fast unverzichtbar.",
    "caspor-akupressurmatte-ganzkoerper": "20 Minuten auf einer Akupressurmatte fühlen sich die ersten Male an wie Folter. Nach zwei Wochen Gewöhnung ist es das entspannendste Ritual des Abends. Durchhalten lohnt sich.",
    "sportneer-ultraleichter-campingstuhl": "280 Gramm, passt in einen Liter Packmaß, hält trotzdem Erwachsene. Für Festivals, Camping, Picknick — ein Stuhl den man wirklich dabei hat weil er nicht nervt.",
    "huch-what-kartenspiel-deutsche-ausgabe": "\"Was würdest du lieber?\" in Spielform — einfach, sozial, lustig. Ideal für Partys oder Abende mit Menschen die man besser kennenlernen will. Kein Vorwissen, sofort spielbar.",
    "suboos-aufladbare-campinglaterne": "Aufladbar statt Batterien ist bei Campingbedarf ein echter Vorteil — keine Überraschungen im Dunkeln. Diese Laterne ist kompakt und hell genug für einen Campingplatz.",
    "tradercat-i-teach-muggles-jutebeutel-lehrer": "Für Lehrer die Harry Potter kennen — ein Geschenk das zeigt dass man nachgedacht hat. Jutebeutel sind praktisch, und dieser hier macht beim nächsten Schulausflug Eindruck.",
    "huzzle-cast-news-metall-knobelpuzzle": "Metall-Puzzles sind für alle die gerne mit den Händen denken. Das Cast News ist knifflig genug dass man nicht in fünf Minuten fertig ist — aber lösbar genug dass man nicht frustriert aufgibt.",
    "interaktives-hundespielzeug-intelligenzspielzeug": "Hunde die sich langweilen machen Unsinn. Dieses Puzzle-Spielzeug beschäftigt sie auf sinnvolle Weise — und wer seinen Hund dabei beobachtet wie er nachdenkt wird es verstehen.",
    "powerball-gyro-handtrainer-original": "Für Kletterer, Musiker, Büromenschen mit Handgelenksproblemen — der Powerball trainiert Unterarme und Handgelenke auf eine Art die kein anderes Gerät erreicht. Suchtpotenzial hoch.",
    "regenbogen-katzenbaelle-24er-set-interaktiv": "24 Bälle ist viel — bis man sieht wie schnell Katzen die unter Möbel schießen. Regenbogenfarben, leicht, interaktiv. Für Katzenbesitzer die ihr Tier beschäftigt halten wollen.",
    "puzzlematte-fuer-1500-3000-teile-puzzles": "Wer ein 2000-Teile-Puzzle anfängt und nicht weiß wo es bleiben soll wenn man unterbricht — das hier ist die Lösung. Einfach aufrollen, verstauen, weiter wenn Zeit ist.",
    "one-piece-ramen-bowl-keramik": "Keramik statt Plastik, Anime-Design, ordentliche Größe — für täglichen Gebrauch besser geeignet als es aussieht. Nicht nur Deko, auch echter Nutzwert.",
    "lunchbox-mit-faechern-1300ml-kinder": "Trennfächer bedeuten dass Obst nicht auf dem Sandwich landet — das ist der einzige Grund den man braucht. Für Kinder die wählerisch sind mit dem Essen: das hier minimiert Beschwerden.",
    "led-schreibtischlampe-mit-gestensteuerung": "Kein Knopf drücken, nur winken — die Gestensteuerung ist tatsächlich nützlicher als erwartet. Wenn die Hände schmutzig sind oder man die Lampe vom Bett aus dimmen will.",
    "krimispiel-escape-room-detektivspiel-erwachsene": "Escape Rooms sind teuer und man braucht eine Gruppe. Dieser Detektiv-Spielabend zu Hause kostet einen Bruchteil und macht ähnlich viel Spaß — wenn man sich darauf einlässt.",
    "ifixit-antistatik-matte-faltbar-esd": "Für alle die Elektronik reparieren oder modifizieren — die antistatische Matte ist kein Luxus sondern Schutz. iFixit ist die Referenz in diesem Bereich, das merkt man an der Qualität.",
    "puzzle-board-2000-teile-mit-8-schubladen": "Acht Schubladen für sortierte Teile und eine feste Oberfläche — wer ernsthaft puzzelt weiß warum das wichtig ist. Für Gelegenheitspuzzler vielleicht überdimensioniert, für Enthusiasten genau richtig.",
    "katzen-fensterliege-haengematte-weich": "Jede Katze will am Fenster sitzen, aber nicht jeder hat Platz für ein Kratzbaum-Monstrum. Diese Fensterliege klemmt an den Rahmen und gibt der Katze ihren Lieblingsplatz ohne den Raum zu dominieren.",
    "dnd-spielleiterschirm-5e-dungeon-master": "Ein guter DM-Schirm mit den richtigen Tabellen auf der richtigen Seite spart im Spiel echte Nachschlage-Zeit. Für alle die regelmäßig leiten — das ist Arbeitswerkzeug, kein Gadget.",
    "digitale-schachuhr-mit-bonus-delay": "Schach ohne Uhr ist Schach ohne Spannung — das ist Geschmackssache. Wer Turnierformate oder einfach faires Zeitmanagement will: diese Uhr hat alle Funktionen die man braucht.",
    "mtg-playmat-mit-wasserdichter-tasche": "Eine Spielmatte schützt die Karten beim Spielen und signalisiert gleichzeitig dass man es ernst meint. Mit wasserdichter Tasche ist der Transport auch kein Problem mehr.",
    "initiative-tracker-acryl-dnd-tabletop": "Aus Acryl, sauber beschriftbar und löschbar — für regelmäßige DnD-Gruppen ist das eine kleine Investition die den Spielablauf ordentlicher macht. Kein Muss, aber ein Komfort.",
    "ita-bag-kawaii-rucksack-mit-display-fenster": "Für Fans die ihre Anstecknadeln und Figuren zeigen wollen — das Konzept des Ita Bags ist das: sichtbare Sammlung. Wer das kennt, weiß warum es das braucht.",
    "rechteckige-lupe-mit-licht-und-standfuss-10x": "10-fache Vergrößerung mit eigener Beleuchtung und Standfuß — für Bastler, Modellbauer, Briefmarkensammler oder alle mit Sehschwäche die kleine Details brauchen. Handfest und nützlich.",
    "sammelkarten-aufbewahrungsbox-fuer-1800-karten": "1800 Karten sind viel — und trotzdem reicht es für manche kaum. Für MTG, Pokémon oder jedes andere TCG ist eine ordentliche Box die Grundlage für eine organisierte Sammlung.",
    "filament-aufbewahrungsbox-3d-druck-6er-pack": "Feuchtes Filament druckt schlecht — das ist Physik. Diese Boxen halten das Filament trocken und sortiert. Für alle die einen 3D-Drucker haben und Qualitätsprobleme lösen wollen.",
    "3d-holzpuzzle-leuchtende-weltkugel": "Basteln und am Ende etwas in der Hand haben das leuchtet — das ist mehr als nur ein Zeitvertreib. Für ruhige Abende oder als besonderes Geschenk das zeigt dass man sich Mühe gemacht hat.",
    "spiral-tastaturkabel-custom-coiled-usb-c": "Optik ist beim eigenen Setup Geschmackssache — aber ein ordentliches Spiralkabel statt einem Plastikchaos macht einen Unterschied. Für Custom-Keyboard-Enthusiasten kein Luxus sondern Abschluss.",
    "adressierbarer-rgb-led-streifen-ws2812b": "WS2812B heißt: du brauchst ein bisschen technisches Know-how. Wenn du das hast, sind diese LED-Streifen der Einstieg in individuelle Beleuchtungsprojekte die kein Fertigprodukt hinkriegt.",
    "astronaut-sternenhimmel-projektor-galaxy": "Sternenhimmel-Projektor der aussieht wie ein Astronaut im Sitzen — das Design ist das erste was auffällt. Die Projektion ist dann tatsächlich gut genug um damit einzuschlafen.",
    "aquarium-deko-landschaft-kunststoff": "Aquarium-Deko ist ein Rabbit Hole — wer anfängt, hört nicht auf. Diese Kunststoff-Landschaft ist solide, säurestabil und sieht unter Wasser besser aus als auf Fotos.",
    "comic-backing-boards-weiss-acid-free": "Wer Comics sammelt und langfristig aufbewahren will — acid-free Boards sind kein optionales Zubehör. Das ist Grundausstattung für alles was Wert behalten soll.",
    "wasserdichte-dry-bag-5l-30l": "Dry Bags sind dann am wichtigsten wenn man sie vergessen hat. Für Kajak, Motorrad, Bergtouren oder einfach als Regenschutz im Rucksack — die Investition lohnt sich schnell.",
    "digitaler-messschieber-edelstahl-150mm": "Ein digitaler Messschieber ist für DIY, 3D-Druck oder Werkstattarbeit präziser und schneller als jede Alternative. Edelstahl bedeutet Langlebigkeit — kein Vergleich zu Plastikversionen.",
    "rpg-charakter-journal-charakterbogen-notizbuch": "Ein Charakterbogen auf Papier ist sicherer, taktiler und ehrlicher als jede App. Wer seinen Charakter durch mehrere Kampagnen begleitet, will das aufgeschrieben haben — ordentlich.",
    "esp32-nodemcu-dev-board-wifi-bluetooth": "Für Maker und Tüftler ist der ESP32 das Standardwerkzeug für IoT-Projekte — WiFi und Bluetooth on board, günstig, riesige Community. Wer damit anfängt hört nicht mehr auf.",
    "katie-cat-suppenkelle-schwarze-katze": "Eine schwarze Katze als Suppenkelle — vollkommen unnötig und trotzdem landet sie in der Küche weil niemand widersteht. Für Katzenliebhaber mit Küchenhumor.",
    "nintendo-game-boy-spardose": "Eine Game-Boy-Spardose ist für alle die mit dem Original aufgewachsen sind ein Nostalgie-Treffer. Münzen einwerfen, lächeln. Reicht als Begründung.",
    "aeropress-go-tragbare-kaffeemaschine": "Die AeroPress ist unter Kaffeeliebhabern seit Jahren Kult — und das Go ist die Reiseversion die wirklich mitkommt. Wer guten Kaffee auch unterwegs will und keine Kapselmaschine nehmen will.",
    "faltbare-wuerfelbretter-doppelseitig-2er-set": "Würfel die vom Tisch fallen unterbrechen jedes Brettspiel. Dieses faltbare Brett verhindert das, passt in die Spielschachtel und stört beim Spielen nicht. Kleines Problem, einfache Lösung.",
    "leselampe-buch-klemme-augenschonend": "Wer spät liest wenn der Partner schläft — diese Klemm-Leselampe ist die richtige Lösung. Warm, nicht zu hell, klemmt an die Seite, kein Kabel das im Weg ist.",
    "baby-groot-blumentopf-figur": "Baby Groot als Blumentopf ist das perfekte Objekt für jeden der Pflanzen und Marvel gleichzeitig mag. Sieht aus als wäre es teuer, ist es aber nicht. Wohnung sofort aufgewertet.",
    "miniaturen-transportkoffer-mit-schloss": "Wer bemalte Miniaturen transportiert kennt das Herzrasen wenn der Koffer aufgeht. Ein richtiger Transportkoffer mit Schaum und Schloss beendet diese Angst. Einmal kaufen, dauerhaft entspannter.",
    "einhell-solarpanel-40w-faltbar-camping": "40 Watt faltbar bedeutet: Laptop, Handy und Powerbank lassen sich auch ohne Steckdose aufladen. Einhell ist eine verlässliche Marke — für längere Camping-Trips oder als Notfallreserve sinnvoll.",
    "retro-buchumschlaege-blumen-buchhuelle-taschenbuecher": "Taschenbücher abnutzen schnell und sehen dann schäbig aus. Diese Buchumschläge schützen und machen aus jedem Buch ein kleines Objekt das man gerne in der Hand hält.",
    "drehbarer-make-up-organizer-3-ebenen": "Drehbar bedeutet dass man nicht alles umstellen muss um hinten zu kommen — das ist der ganze Trick. Drei Ebenen, 360 Grad, und die Schminke bleibt endlich dort wo sie hingehört.",
    "funko-pop-darth-vader-star-wars": "Funko Pops sind entweder alles oder nichts — wer sie sammelt braucht Darth Vader. Wer sie nicht sammelt versteht das nicht. Für alle aus der ersten Gruppe: hier.",
    "vintage-popcorn-maschine-retro-cart": "Eine echte Popcornmaschine ist mehr als ein Gadget — sie ist ein Statement für Filmabende zu Hause. Das Retro-Design macht sie zum Dekostück das gleichzeitig funktioniert. Für Kinoliebhaber.",
    "elektrischer-anspitzer-6-loch-mit-behaelter": "Sechs Lochgrößen für verschiedene Stifte, Behälter der Späne auffängt — für Künstler, Lehrer oder alle die regelmäßig Bleistifte benutzen ist das einfach besser als Handanspitzer.",
    "uv-led-nagellampe-gel-naegel-mit-timer": "Gel-Nägel zuhause sind mit der richtigen Lampe tatsächlich machbar — und diese hier hat Timer und mehrere Intensitätsstufen. Wer regelmäßig zum Nagelstudio geht rechnet schnell aus was das einspart.",
    "haustier-kamera-360-mit-app": "Das Tier alleine zuhause lassen und dabei live zuschauen — die 360-Grad-Kamera macht das möglich ohne im ganzen Raum Kameras zu verteilen. Für alle die beim ersten Mal loslassen Schwierigkeiten haben.",
    "gan-356me-speed-cube-3x3-magnetisch": "Der GAN 356 ME ist unter Speedcubern ein Standardwerkzeug — magnetisch bedeutet smoother, präziser, schneller. Für ernsthafte Speedcuber kein Kompromiss, für Einsteiger vielleicht überdimensioniert.",
    "minecraft-fuchs-nachtlicht-offiziell": "Offizielle Minecraft-Lizenz bedeutet hier tatsächlich bessere Qualität als die üblichen Imitate. Für Minecraft-Fans im Kinderzimmer das Nachtlicht das Sinn macht.",
    "minecraft-schwein-spardose-19cm": "Oink. Das ist alles was man sagen muss. Für Minecraft-Fans gibt es keine Alternative — diese Spardose kommt auf den Schreibtisch, fertig.",
    "power-tower-klimmzugstange-faltbar": "Klimmzüge, Dips, Liegestütze — und faltbar wenn man fertig ist. Für alle die zuhause trainieren wollen ohne ein Gerät das den halben Raum einnimmt. Solide Grundausstattung.",
    "magnetische-bausteine-150-teile-ab-4-jahre": "Magnetische Bausteine sind die ehrlichste STEM-Förderung die man kaufen kann — kein Tutorial, kein Bildschirm, nur Bauen. 150 Teile bedeutet dass die Ideen nicht ausgehen.",
    "gan-i4-smart-cube-magnetisch-bluetooth": "Einen Bluetooth-Zauberwürfel der deine Züge trackt kannte man vor fünf Jahren nicht. Jetzt gibt es ihn und er macht Speedcubing zu einem Trainingsprogramm. Für alle die es wirklich wollen.",
    "ps5-horizontale-tasche-tragetasche": "Die PS5 ist unhandlich — das ist Fakt. Eine Tasche die sie schützt und den Transport erleichtert ist für alle die sie zum Freund mitnehmen kein Luxus. Horizontal passt sie besser rein.",
    "personalisierte-holz-spardose-kinder": "Holz, personalisiert, mit eigenem Namen — das ist eine Spardose die man nicht wegschmeißt. Für Kinder als Geschenk mit echtem Wert, nicht nur als Einmal-Überraschung.",
    "vogelspielzeug-nymphensittich-wellensittich": "Vögel die sich langweilen zupfen Federn oder schreien — beides ist vermeidbar. Dieses Spielzeug beschäftigt sie auf die Art wie sie es brauchen: zum Knabbern, Klettern, Entdecken.",
    "hitster-musikquiz-partyspiel": "Scan den QR-Code, Song spielt ab, rate den Jahrgang — einfacheres Spielprinzip gibt es kaum. Und trotzdem entstehen dabei Diskussionen die bis Mitternacht gehen.",
    "handventilator-akku-aufladbar-mini": "Kleiner Ventilator in der Tasche klingt nach Luxusproblem — bis man ihn im vollen Bus oder beim Festival dabei hat. Dann ist er das Beste.",
    "lego-harry-potter-qualitaet-quidditch": "LEGO Harry Potter trifft einen Nerv bei allen die mit dem Buch aufgewachsen sind. Das Quidditch-Set ist komplex genug um wirklich Spaß beim Bauen zu machen und danach gut auszusehen.",
    "lego-botanicals-orchidee-kunstpflanze": "Für alle die Pflanzen lieben aber sie regelmäßig umbringen — LEGO Botanicals ist die ehrliche Lösung. Sieht aus wie eine echte Pflanze, braucht kein Wasser, fällt nicht um.",
    "wer-ist-es-marvel-edition-brettspiel": "Wer ist es kennt jeder aus der Kindheit. Die Marvel-Edition macht das Spielprinzip für Fans interessanter — weil man bei Doctor Strange oder Black Widow einfach mehr Spaß hat als bei Standard-Gesichtern.",
    "plasmakugel-8-zoll-beruehrungsempfindlich": "8 Zoll Plasma und berührungsempfindlich — das Ding zieht jeden an. Als Dekoobjekt im Zimmer ist es eines dieser Sachen die Besuch immer anfassen muss. Eigentlich für Kinder, ehrlich gesagt für alle.",
    "toilettenbuerste-gag-geschenk-set-lustig": "Als Geschenk für Menschen mit Sinn für Humor ist eine außergewöhnliche Toilettenbürste das perfekte Mitbringsel — niemand erwartet es, jeder benutzt es danach tatsächlich.",
    "deadpool-spardose-bueste-marvel": "Deadpool als Spardose ist konsequent — er macht Witze über alles, auch über das Sparen. Für Fans kein Wahlrecht, für alle anderen ein guter Gesprächsstarter im Regal.",
    "the-army-painter-wet-palette-tabletop": "Wer Miniaturen bemalt weiß wie schnell Farbe auf der normalen Palette eintrocknet. Eine Wet Palette hält sie stunden- bis tagelang frisch — das verändert den Arbeitsprozess grundlegend.",
    "einweg-urinbeutel-frauen-unterwegs": "Kein Charme-Produkt, aber eines das Frauen auf Reisen, Festivals oder langen Fahrten echte Freiheit gibt. Wer das schon mal gebraucht und nicht hatte, kauft das sofort.",
    "harry-potter-selbstruehrende-tasse-zauberstab": "Die Tasse rührt sich selbst, der Zauberstab liegt daneben — für Harry Potter Fans ist das ein Moment der Kindheit in Produktform. Kein tieferer Sinn nötig.",
    "5-in-1-elektrischer-wein-dekanter-smart": "Wein dekantieren dauert normalerweise Stunden. Dieser elektrische Dekanter tut das in Minuten — ob man den Unterschied schmeckt ist Geschmackssache, aber der Komfort ist real.",
    "bug-a-salt-3-0-fliegenjaeger-salzgewehr": "Ein Salzgewehr gegen Fliegen. Kein chemischer Spray, kein lautloser Tod — stattdessen Sport und Befriedigung. Jeder Haushalt mit Fliegen-Problem sollte das zumindest einmal ausprobieren.",
    "mr-bear-family-bartoel-tiki-punch": "Bartöl ist Bartpflege für alle die keinen Bart-Podcast hören aber trotzdem wissen dass Pflege einen Unterschied macht. Mr Bear Family macht gute Produkte — Tiki Punch riecht dabei tatsächlich gut.",
    "snoop-dogg-kochbuch-from-crook-to-cook": "Snoop Dogg hat ein ernsthaftes Kochbuch geschrieben und es ist überraschend gut. Echte Rezepte, eigener Stil, kein Werbezweck. Für alle die Kochen und Humor vereinen wollen.",
    "relaxdays-tierpinata-set": "Piñata aufhängen, Kind blind binden, draufschlagen lassen — das ist das simpelste und zuverlässigste Unterhaltungsformat für Kindergeburtstage. Dieser Aufwand ist minimal, der Spaßfaktor nicht.",
    "personalisierter-kinder-riegel-xxl-30er": "30 Kinder Riegel mit eigenem Namen drauf — das ist das Geschenk das sowohl bei Kindern als auch Erwachsenen ankommt. Schokolade + Personalisierung = unschlagbare Kombination.",
    "frittierte-regenwuermer-aus-der-dose": "Der Gag funktioniert genau einmal — aber dieser eine Moment ist es wert. Wer jemanden kennt dem man eine Dose frittierte Würmer hinhalten kann, sollte diese Chance nicht lassen.",
    "sudoku-klopapier-toilettenpapier": "Produktivität auf der Toilette. Klingt absurd, stimmt aber. Wer Sudoku mag und die stille Auszeit nutzen will statt das Handy rauszuholen — das hier ist die analoge Alternative.",
    "layersmith-schaf-toilettenpapierhalter": "Ein Schaf-Klorollenhalter der stapelbar ist und gut aussieht — Made in Germany, Bio-Plastik, sinnvolles Design. Manchmal ist das Kurioseste auch das Durchdachte.",
    "dh-fitlife-verstellbare-kurzhantel-18kg": "12 Gewichtsstufen in einer Hantel — wer keinen Platz für ein halbes Hantelregal hat und trotzdem ernsthaft trainieren will, dem nimmt dieser Kompromiss nichts weg. Im Gegenteil.",
    "mygesi-sneaker-wipes-schuh-reiniger": "Weiße Sohlen bei Regen tragen? Mit diesen Tüchern kein Drama mehr. Wir haben sie im Portemonnaie — für genau den Moment wenn es zu spät ist und man trotzdem noch etwas retten will.",
    "wolfbox-megaflow-elektrischer-druckluft-reiniger": "Druckluft-Dosen sind teuer, umweltschädlich und leer wenn man sie braucht. Dieser elektrische Ersatz ist einmalig gekauft und funktioniert danach einfach immer. Für PC-Nutzer und Kamera-Besitzer.",
    "silikon-magnete-airfryer-backpapier-4er-set": "Das Backpapier fliegt im Airfryer auf das Essen — kennt jeder. Diese vier Silikon-Magnete lösen das Problem für einstellige Euro-Beträge. Einer dieser Käufe die man sofort vergisst weil sie einfach funktionieren.",
    "charmofun-ninja-airfryer-zubehoer-28-stueck": "28 Teile klingt nach zu viel — ist es aber nicht wenn man sieht wie viele davon wirklich gebraucht werden. Für Ninja Dual Zone Besitzer ist das die Zubehörbox die man einmal kauft und dann nicht mehr denkt.",
    "joymoop-mopp-eimer-set-haendefrei": "Wischen ohne nasse Hände — der Unterschied klingt klein ist aber spürbar. Wer einmal mit einem Ausdrück-Eimer-System geputzt hat will nicht zurück zum alten Chaos.",
    "schluesselfinder-4-empfaenger-led-30m": "Schlüssel weg, Fernbedienung weg — wer das kennt versteht dieses Produkt sofort. Drücken, Piepen folgen, gefunden. Kein Bluetooth-Pairing, keine App, keine Abos. Einfach funktionieren.",
    "pop-up-geburtstagskarte-musik-licht-feuerwerk": "Eine Karte die aufgeht und dann Feuerwerk macht, Musik spielt und leuchtet — das ist keine Karte mehr, das ist ein Moment. Für alle die mehr wollen als unterschriebenes Papier.",
    "scheisse-geparkt-notizblock-2er-set": "Konstruktiver Umgang mit rücksichtslosem Parken. Ob es was ändert? Unwahrscheinlich. Ob es hilft die Frustration zu kanalisieren? Auf jeden Fall.",
    "regaine-maenner-minoxidil-3-monatspackung": "Minoxidil funktioniert — das ist klinisch belegt. Drei Monate sind der erste Zyklus um echte Ergebnisse zu sehen. Wer anfängt sollte wissen: Geduld ist Teil der Therapie, kein Bug.",
    "recovry-dermaroller-maenner-haarwachstum": "Kombiniert mit Minoxidil zeigen Dermaroller in Studien deutlich bessere Resultate als Minoxidil allein. Das Prinzip ist einfach — Mikroverletzungen aktivieren Heilungsprozesse. Klingt brutal, ist es nicht.",
    "dh-fitlife-verstellbare-kurzhantel-18kg": "12 Gewichtsstufen in einer Hantel — wer keinen Platz für ein halbes Hantelregal hat und trotzdem ernsthaft trainieren will, dem nimmt dieser Kompromiss nichts weg. Im Gegenteil.",
    "mygesi-sneaker-wipes-schuh-reiniger": "Weiße Sohlen bei Regen tragen? Mit diesen Tüchern kein Drama mehr. Wir haben sie im Portemonnaie — für genau den Moment wenn es zu spät ist und man trotzdem noch etwas retten will.",
    "wolfbox-megaflow-elektrischer-druckluft-reiniger": "Druckluft-Dosen sind teuer, umweltschädlich und leer wenn man sie braucht. Dieser elektrische Ersatz ist einmalig gekauft und funktioniert danach einfach immer. Für PC-Nutzer und Kamera-Besitzer.",
    "silikon-magnete-airfryer-backpapier-4er-set": "Das Backpapier fliegt im Airfryer auf das Essen — kennt jeder. Diese vier Silikon-Magnete lösen das Problem für einstellige Euro-Beträge. Einer dieser Käufe die man sofort vergisst weil sie einfach funktionieren.",
    "charmofun-ninja-airfryer-zubehoer-28-stueck": "28 Teile klingt nach zu viel — ist es aber nicht wenn man sieht wie viele davon wirklich gebraucht werden. Für Ninja Dual Zone Besitzer ist das die Zubehörbox die man einmal kauft und dann nicht mehr denkt.",
    "joymoop-mopp-eimer-set-haendefrei": "Wischen ohne nasse Hände — der Unterschied klingt klein ist aber spürbar. Wer einmal mit einem Ausdrück-Eimer-System geputzt hat will nicht zurück zum alten Chaos.",
    "schluesselfinder-4-empfaenger-led-30m": "Schlüssel weg, Fernbedienung weg — wer das kennt versteht dieses Produkt sofort. Drücken, Piepen folgen, gefunden. Kein Bluetooth-Pairing, keine App, keine Abos. Einfach funktionieren.",
    "pop-up-geburtstagskarte-musik-licht-feuerwerk": "Eine Karte die aufgeht und dann Feuerwerk macht, Musik spielt und leuchtet — das ist keine Karte mehr, das ist ein Moment. Für alle die mehr wollen als unterschriebenes Papier.",
    "scheisse-geparkt-notizblock-2er-set": "Konstruktiver Umgang mit rücksichtslosem Parken. Ob es was ändert? Unwahrscheinlich. Ob es hilft die Frustration zu kanalisieren? Auf jeden Fall.",
}

def update_note(slug, note):
    url = f"{SUPABASE_URL}/rest/v1/products?slug=eq.{slug}"
    resp = requests.patch(url, headers=HEADERS, json={"editorial_note": note})
    return resp.status_code

total = len(notes)
success = 0
failed = []

for i, (slug, note) in enumerate(notes.items(), 1):
    status = update_note(slug, note)
    if status in (200, 204):
        success += 1
        print(f"[{i}/{total}] ✓ {slug}")
    else:
        failed.append(slug)
        print(f"[{i}/{total}] ✗ {slug} (status {status})")
    time.sleep(0.1)

print(f"\n=== Fertig: {success}/{total} erfolgreich ===")
if failed:
    print(f"Fehlgeschlagen: {failed}")
